pipeline {
  agent { label 'master' }
  environment {
    appName = "variable" 
  }
  stages {
        stage('Prepare Build') {
           steps {
                  echo "build"
                }
            }
            stage {
                stage('Build') {
                    steps {
                        /*sh 'yarn install'*/
                        echo 'yarn install'
                    }
                }
                stage('Lint') {
                    steps {
                        echo "yarn lint"
                        /*sh 'yarn lint'*/
                    }
                }
            }
        }

  }
  post {
      always {          
          deleteDir()
           sh "echo 'fase always'"
      }
      success {
            sh "echo 'fase success'"
        }

      failure {
            sh "echo 'fase failure'"
      }
      
  }




