pipeline {
  agent { label 'master' }
  environment {
    appName = "variable" 
  }
  stages {
    stage('Notify') {
            when { anyOf { branch 'develop'; branch 'demo' } }
            steps {
                slackSend( channel: "#tramiteya", color: '#FFFF00', message: ":crossed_fingers::skin-tone-5: STARTED: Build ${env.JOB_NAME} [${env.BUILD_NUMBER}] (<${env.RUN_DISPLAY_URL}|Open>)")
            }
        }
        stage('Prepare Build') {
            agent {
                docker {
                    image 'darkj24/node-gyp-compatible:1.0'
                    args '-v $HOME/docker-images-cached:/root/docker-images-cached'
                }
            }
            stages {
                stage('Build') {
                    steps {
                        sh 'yarn install'
                    }
                }
                stage('Lint') {
                    steps {
                        sh 'yarn lint'
                    }
                }
            }
        }

  }
  post {
      always {          
          deleteDir()
           sh "echo 'fase always'"
      }
      success {
            sh "echo 'fase success'"
        }

      failure {
            sh "echo 'fase failure'"
      }
      
  }
}  




